## Working with PyTorch

PyTorch (or just _torch_) is a popular open-source library for Python that is commonly used for machine learning and AI tasks. It provides many features and functions and is widely used by many people. It was originally developed by Meta Inc., but is currently maintained by the PyTorch Foundation, which is a subsidiary of the Linux Foundation.

You can read more about torch here: https://pytorch.org/

PyTorch has many features, but we will focus on using _Tensor_s and running code on the GPU.

First, we need to install and import `torch`:

In [10]:
%pip install torch
import torch

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Next, we need to check if a GPU is available. After that, we can create the `device` and print the name of the device.

The device determines where PyTorch stores data and where it performs computations. In this case, we use the device `cuda:0`. This refers to the CUDA GPU with index 0 that is available on the system.

In [11]:
print("GPU available:", torch.cuda.is_available())

# Initialize the device
device = torch.device("cuda:0")

# Print the name
name = torch.cuda.get_device_name(device)
print(f"GPU detected: {name}")


GPU available: True
GPU detected: NVIDIA A100-SXM4-40GB


Next, we create a `tensor`. A tensor is similar to a NumPy array. We can create a tensor using `torch.tensor`, where we need to specify that we want the data on the GPU using `device=device`.

In [12]:
# Create tensor on the GPU containing the numbers [1,2,3,4]
x = torch.tensor([1.0, 2, 3, 4], device=device)

# Print the number of elements
print(x.numel())

# Print the data type of the elements
print(x.dtype)

4
torch.float32


To convert a NumPy array into a PyTorch tensor, we can use the function `torch.tensor`. To convert it back to a NumPy array, we can use the function `tensor.cpu().numpy()`.

In [13]:
import numpy as np

# Create numpy array
a = np.array([5, 6, 7, 8])
print(a)

# Convert numpy -> torch
b = torch.tensor(a).to(device)
print(b)

# Copy CPU -> GPU
c = b.cpu() # or .to("cpu")
print(c)

# Convert back to numpy array
d = c.numpy()
print(d)

[5 6 7 8]
tensor([5, 6, 7, 8], device='cuda:0')
tensor([5, 6, 7, 8])
[5 6 7 8]


There are also many ways to create a tensor directly on the GPU, many are similar to functions in NumPy. Here are some examples.

In [14]:
# There are many ways to create a tensor
a = torch.zeros(10, device=device)
print(f"{a=}")

b = torch.ones(10, device=device)
print(f"{b=}")

c = torch.rand(10, device=device)
print(f"{c=}")

d = torch.empty(10, device=device)
print(f"{d=}")

e = torch.arange(10, device=device)
print(f"{e=}")

f = torch.linspace(0, 1, 10, device=device)
print(f"{f=}")

a=tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
b=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')
c=tensor([0.1892, 0.7776, 0.7495, 0.4807, 0.1895, 0.0227, 0.2254, 0.3137, 0.1853,
        0.9881], device='cuda:0')
d=tensor([0.1892, 0.7776, 0.7495, 0.4807, 0.1895, 0.0227, 0.2254, 0.3137, 0.1853,
        0.9881], device='cuda:0')
e=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')
f=tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000], device='cuda:0')


Tensors can be multi-dimensional. They can be 1-dimensional (vector), 2-dimensional (matrix), 3-dimensional, ...

In [15]:
x = torch.rand(3, device=device)
print(x[0])

y = torch.rand((3, 3), device=device)
print(y[0,0])

z = torch.rand((3, 3, 3), device=device)
print(z[0,0,0])

tensor(0.1726, device='cuda:0')
tensor(0.0053, device='cuda:0')
tensor(0.6303, device='cuda:0')


Slicing is also supported:

In [16]:
x = torch.rand(5, 5, device=device)

# This is our matrix
print(x)

# Print the first row
print(x[0,:])

# Print the first column
print(x[:,0])

tensor([[0.5678, 0.1915, 0.8374, 0.9535, 0.9907],
        [0.2867, 0.2255, 0.9078, 0.8415, 0.4390],
        [0.6318, 0.1021, 0.1293, 0.7463, 0.9831],
        [0.1683, 0.0102, 0.3473, 0.0018, 0.1802],
        [0.0273, 0.6376, 0.0896, 0.3047, 0.7267]], device='cuda:0')
tensor([0.5678, 0.1915, 0.8374, 0.9535, 0.9907], device='cuda:0')
tensor([0.5678, 0.2867, 0.6318, 0.1683, 0.0273], device='cuda:0')


Tensors also support many operations.

In [17]:
# You can also do common operations on tensors
x = torch.arange(10, device=device)
y = torch.arange(10, device=device)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(torch.sqrt(x))
print(torch.exp(x))
print(torch.sin(x))

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], device='cuda:0')
tensor([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284,
        3.0000], device='cuda:0')
tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03], device='cuda:0')
tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894,  0.4121], device='cuda:0')


Be aware that you cannot mix NumPy arrays and PyTorch tensors in these operations:

In [18]:
x = torch.rand(10, device=device)
y = np.arange(10)

try:
    print(x + y)
except Exception as e:
    print(e)

# This returns a tensor on the CPU
print(x.cpu() + y)

# This returns a numpy array
print(x.cpu().numpy() + y)

# This returns a tensor on the GPU
print(x + torch.tensor(y, device=device))

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
tensor([0.0452, 1.2428, 2.9803, 3.7192, 4.2936, 5.5925, 6.5862, 7.6702, 8.4497,
        9.5942], dtype=torch.float64)
[0.04524009 1.24281727 2.98026043 3.71916705 4.293625   5.59246826
 6.58616304 7.6702038  8.44969147 9.59424245]
tensor([0.0452, 1.2428, 2.9803, 3.7192, 4.2936, 5.5925, 6.5862, 7.6702, 8.4497,
        9.5942], device='cuda:0')


/scratch-local/sheldens.20694722/ipykernel_3251276/3587019952.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(x.cpu() + y)


An important feature of PyTorch is the `@torch.compile` decorator. This decorator tells PyTorch to compile a Python function into a more optimized version before executing it. Instead of running the function line-by-line in Python, PyTorch analyzes the operations inside the function and builds a more efficient computation graph. It can then apply various optimizations, such as fusing multiple operations together, reducing memory usage, and generating more efficient GPU kernels.

This process can significantly improve performance, especially for functions that perform many tensor operations. The compiled function can therefore run much faster than the original Python version, while keeping the code easy to read and write.

Below is a simple example. We create two large tensors on the GPU and define a function that performs several mathematical operations on them. By adding the `@torch.compile` decorator, PyTorch will attempt to optimize the function automatically.

In [19]:
@torch.compile
def compute(a, b):
    return (a + b) + torch.sin(a) * torch.cos(b)
    
a = torch.rand(1_000_000, device=device)
b = torch.rand(1_000_000, device=device)
c = compute(a, b)

# Larger example

Now, we are going to see a larger example of how to use PyTorch. For this, we will generate `n` random planets and one sun. Next, we calculate the force that each planet experiences from the sun using Newton's law of universal gravitation.

We start by generating `n` random planets in a 2 dimensional plane. The x and y coordinates are randomly in the range `[0, 1]`.

Next, we will place the sun at position `(0.5, 0.5)`.

In [36]:
n = 10
position = torch.rand((2, n), device=device)
mass = torch.rand(n, device=device) + 100
sun_pos = [0.5, 0.5]
G = 6.67e-11

In [22]:
import matplotlib.pyplot as plt

plt.axis("equal")
plt.scatter(
    position[0].cpu(),  # Don't forget .cpu()
    position[1].cpu(),
)

sun_pos = (0.5, 0.5)

plt.scatter(
  sun_pos[0],
  sun_pos[1],
  s=1000,
)

ImportError: /gpfs/admin/_hpc/sw/arch/INTEL-AVX512/RHEL9/EB_production/2024/software/GCCcore/13.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/13.3.0/../../../../lib64/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /sw/arch/RHEL9/EB_production/2025/software/matplotlib/3.10.3-gfbf-2025a/lib/python3.13/site-packages/matplotlib/_c_internal_utils.cpython-313-x86_64-linux-gnu.so)

In [37]:
def calculate_forces(pos, mass):
    diffx = pos[0] - sun_pos[1] # Scalar - Tensor
    diffy = pos[0] - sun_pos[1]
    diff = torch.stack([diffx, diffy])
    
    distance = diff.norm(dim=0)
    direction = diff / distance
    
    magnitude = G * mass / distance**2
    
    forces = magnitude * direction
    return forces

forces = calculate_forces(position, mass)

In [ ]:
import matplotlib.pyplot as plt

n = 10
position = torch.rand((2, n), device=device)
mass = torch.rand(n, device=device) + 100

plt.axis("equal")
plt.scatter(
  position[0].cpu(),
  position[1].cpu(),
)


plt.scatter(
  sun_pos[0],
  sun_pos[1],
  s=1000,
)



plt.quiver(
  planet_pos[0].cpu(),
  planet_pos[1].cpu(),
  forces[0].cpu(),
  forces[1].cpu()
)

# Comparison between NumPy, CuPy and PyTorch

In [38]:
# First, compute it using NumPy
import numpy as np

n = 10_000_000
pos = np.random.rand(2, n)
mass = np.random.rand(n)

def calculate_forces(pos, mass):
  diff = np.stack([sun_pos[0] - pos[0], sun_pos[1] - pos[1]])
  distance = np.linalg.norm(diff, axis=0)
  return G * mass * diff / distance**3

%timeit -n1 -r1 calculate_forces(pos, mass)

379 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [ ]:
# Next, compute it using Cupy
%pip install cupy
import cupy

n = 10_000_000
pos = cupy.random.rand(2, n)
mass = cupy.random.rand(n)

def calculate_forces(pos, mass):
  diff = cupy.stack([sun_pos[0] - pos[0], sun_pos[1] - pos[1]])
  distance = cupy.linalg.norm(diff, axis=0)
  return G * mass * diff / distance**3

%timeit -n5 calculate_forces(pos, mass); cupy.cuda.stream.get_current_stream().synchronize()

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 102.9 MB/s eta 0:00:00


In [ ]:
# Finally, compute it using pytorch
n = 10_000_000
pos = torch.rand(2, n, device=device)
mass = torch.rand(n, device=device)

def calculate_forces(pos, mass):
  diff = torch.stack([sun_pos[0] - pos[0], sun_pos[1] - pos[1]])
  distance = diff.norm(dim=0)
  return G * mass * diff / distance**3

%timeit -n5 calculate_forces(pos, mass); torch.cuda.synchronize()

In [ ]:
# We can use torch.compile to speed things up!
n = 10_000_000
pos = torch.rand(2, n, device=device)
mass = torch.rand(n, device=device)

@torch.compile
def calculate_forces(pos, mass):
  diff = torch.stack([sun_pos[0] - pos[0], sun_pos[1] - pos[1]])
  distance = torch.sqrt(diff[0]**2 + diff[1]**2)
  return G * mass * diff / distance**3

%timeit -n5 calculate_forces(pos, mass); torch.cuda.synchronize()

# Autodiff (gradients, derivatives) [only if there is time]

In [ ]:
# Print the input
x = torch.tensor(5.0, device=device, requires_grad=True)
print(f"{x=}")

# Print the output
y = x ** 2
print(f"{y=}")

# Print the derivative dy/dx
y.backward()
print(f"{x.grad=}")

In [ ]:
# Print the input
x = torch.rand(10, device=device, requires_grad=True)
print(f"{x=}")

# Print the output
y = torch.sum(torch.sqrt(x) ** torch.sin(x))
print(f"{y=}")

# Print the derivative dy/dx for each x[i]
y.backward()
print(f"{x.grad=}")

# [OLD] Real world example

In [ ]:
# @title
n = 10
pos = torch.rand((2, n), device=device)
mass = torch.rand(n, device=device) * 100 + 50

import matplotlib.pyplot as plt
plt.axis("equal")
plt.scatter(pos[0].cpu(), pos[1].cpu(), s=mass.cpu())

In [ ]:
# @title
def gravitational_force_field(pos, mass):
    G = 6.67e-11
    diff = pos[:,None,:] - pos[:,:,None]  # (2, N, N)
    distance = diff.norm(dim=0)
    forces = G * mass * diff * distance ** -3
    return torch.nansum(forces, dim=2)

force = gravitational_force_field(pos, mass)

import matplotlib.pyplot as plt
plt.axis("equal")
plt.scatter(pos[0].cpu(), pos[1].cpu(), s=mass.cpu())
plt.quiver(pos[0].cpu(), pos[1].cpu(), force[0].cpu(), force[1].cpu())

In [ ]:
# @title
n = 5000
pos = torch.rand((2, n), device=device)
mass = torch.rand(n, device=device) * 100 + 50
f = torch.compile(gravitational_force_field)

%timeit -n5 force = gravitational_force_field(pos, mass).cpu()
%timeit -n5 force = f(pos, mass).cpu()

# [OLD] Comparison of Numpy, CuPy, and PyTorch

In [ ]:
# @title
# First, compute it using NumPy
import numpy

x = numpy.random.rand(100_000_000).astype("float32")
y = numpy.random.rand(100_000_000).astype("float32")

def calculate_z(x, y):
  return (x + y) * 2 + numpy.sin(x) * numpy.cos(y)

%timeit -n1 -r1 calculate_z(x, y)

In [ ]:
# @title
# Next, compute it using CuPy
import cupy

x = cupy.random.rand(100_000_000).astype("float32")
y = cupy.random.rand(100_000_000).astype("float32")

def calculate_z(x, y):
  return (x + y) * 2 + cupy.sin(x) * cupy.cos(y)

%timeit -n10 calculate_z(x, y); cupy.cuda.stream.get_current_stream().synchronize()

In [ ]:
# @title
# Finally, compute it using PyTorch
import torch

x = torch.randn(100_000_000, device=device).type(torch.float32)
y = torch.randn(100_000_000, device=device).type(torch.float32)
print(x.dtype)

def calculate_z(x, y):
  return (x + y) * 2 + torch.sin(x) * torch.cos(x)

%timeit -n10 calculate_z(x, y); torch.cuda.synchronize()

In [ ]:
# @title
# We can get even more performance by using @torch.compile
import torch

x = torch.randn(100_000_000, device=device).type(torch.float32)
y = torch.randn(100_000_000, device=device).type(torch.float32)
print(x.dtype)

@torch.compile
def calculate_z(x, y):
  return (x + y) * 2 + torch.sin(x) * torch.cos(y)

calculate_z(x, y)

%timeit -n10 calculate_z(x, y); torch.cuda.synchronize()